### ISSUE TITLE
No warning for illegal content in the scenario selector for chub.

### ISSUE THREAD

**Issue by ProtoBelisarius** [LostRuins/lite.koboldai.net#46]
My country would classify multiple (currently 6 on the frontpage) cards from chub ai as CSAM and illegal. 
Please add a warning like "May contain content illegal in your country." or something for newbies.  I did not know of the completely unmoderated nature of this site and would have never visited it knowingly.

**Comment by henk717** [comment]
Chub's TOS comply with the UK law which is already one of the stricter countries. Their website is highly active and most of the content on their frontpage is new content.

If you find content that is in violation you can report it to them to help them with the moderation. Our own UI's import feature only accepts links that the user has already visited and wishes to import.

If you wish to discuss the moderation I recommend visiting the chub discord https://discord.gg/chubai to report content to their moderation team as we have no control over third party content.

**Comment by ProtoBelisarius** [comment]
I went to their discord first, before opening this issue. They explicitly said that this content was not only allowed but would never be moderated as long as no "uncensored pictures were shared". And that the platform was created to share cards of all kinds. 

**Please delete this issue entirely, I do not feel comfortable to even associate with a project that condones this type of content.**

**Comment by LostRuins** [comment]
> I went to their discord first, before opening this issue. They explicitly said that this content was not only allowed but would never be moderated as long as no "uncensored pictures were shared". And that the platform was created to share cards of all kinds.
>
> Please delete this issue entirely, I do not feel comfortable to even associate with a project that condones this type of content.

I don't think it's fair to say we "Condone this type of content". In fact, let me be clear that we do NOT condone CSAM content! 

That said, Kobold Lite UI is just a tool, and like any other tool it can be used for good or bad purposes by different people. A kitchen knife can be used to chop carrots, peel potatoes or stab people, but it is unfair to fault the supermarket or shop because a knife was used as a murder weapon. Likewise you can use Microsoft Word to write your thesis or to write hate messages, but you cannot blame Microsoft if someone uses their tool to write a manifesto.

As henk said, Chub AI is an independent third-party website that is responsible for the content that they host, and users are themselves responsible for how they use it, including the links they decide to import. I am sure there are plenty of legitimate users with legal cards that use that platform to share their content. 

That said, it is your prerogative to stop using this project if it makes you feel uncomfortable. Also this is a free and open source project, so feel free to fork it and modify your own version to suit your personal use cases.
